server:
  port: 9010

spring:
  application:
    name: zillow-llm
  profiles:
    active: mongodb, redis
  cloud:
    config:
      uri: http://localhost:9010
      label: master
      name: zillow
      profile: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB

management:
  endpoints:
    web:
      exposure:
        include: refresh

langchain4j:
  open-ai.chat-model:
    log-requests: true
    log-responses: true

logging:
  pattern:
    console: '%d{MM/dd HH:mm:ss.SSS} %clr(%-5level) ---  [%-15thread] %cyan(%-50logger{50}):%msg%n'
  level:
    dev:
      langchain4j: DEBUG
      ai4j:
        openai4j: DEBUG