server:
  port: 9010

spring:
  application:
    name: zillow-llm
  profiles:
    active: mongodb, redis
  cloud:
    config:
      uri: http://zillow-config-server:3355
      label: master
      name: zillow
      profile: prd
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB

management:
  endpoints:
    web:
      exposure:
        include: refresh

langchain4j:
  open-ai.chat-model:
    log-requests: true
    log-responses: true

logging:
  level:
    dev:
      langchain4j: DEBUG
      ai4j:
        openai4j: DEBUG