server:
  port: 9000

spring:
  application:
    name: zillow-file
  profiles:
    active: mongodb
  cloud:
    config:
      uri: http://localhost:9010
      label: master
      name: zillow
      profile: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB

management:
  endpoints:
    web:
      exposure:
        include: refresh

fdfs:
  so-timeout: 10000
  connect-timeout: 10000
  fileUrl: http://111.231.19.137:8888/
  tracker-list:
    - 111.231.19.137:22122

zillow:
  fdfsBasePath:
    nginx:
      prefix: http://111.231.19.137:8888/
  banner:
    nginx:
      prefix: http://111.231.19.137:8888/
