FROM java:8
MAINTAINER "palpatine"
ADD ./zillow-eureka-0.0.1-SNAPSHOT.jar /home
WORKDIR /home
ENV EUREKA_HOME=/home/zillow-eureka-0.0.1-SNAPSHOT.jar
ENV PATH=$PATH:$EUREKA_HOME/bin
EXPOSE 2375
CMD java -jar home/zillow-eureka-0.0.1-SNAPSHOT.jar && tail -F /home/zillow-eureka-0.0.1-SNAPSHOT.jar/bin/catalina.bat