spring:
  data:
    mongodb:
      # host: percival.services
      host: localhost
      port: 27017
      username: root
      password: root
      database: zillow
      authentication-database: admin