server:
  port: 9020

spring:
  application:
    name: zillow-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Palpatine0/Zillow.git
          search-paths:
            - zillow-config
      label: master