server:
  port: 9010
spring:
  application:
    name: zillow-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Palpatine0/Zillow.git
          search-paths:
            - zillow-config
      label: master
#eureka:
#  client:
#    service-url:
#      defaultZone: http://111.231.19.137:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  pattern:
    console: '%d{MM/dd HH:mm:ss.SSS} %clr(%-5level) ---  [%-15thread] %cyan(%-50logger{50}):%msg%n'