server:
  port: 9007

spring:
  application:
    name: zillow-user
  profiles:
    active: redis,mongodb
  cloud:
    config:
      uri: http://percival.services:3355
      label: master
      name: zillow
      profile: prd