server:
  port: 9003

spring:
  profiles:
    active: mongodb,fdfsBasePathNginx
  application:
    name: zillow-search
  elasticsearch:
    uris: http://111.231.19.137:9200

zillow:
  search:
    init:
      enabled: true