server:
  port: 9003

spring:
  profiles:
    active: mongodb, itemCacheName
  application:
    name: zillow-search
  elasticsearch:
    uris: http://percival.services:9200

zillow:
  search:
    init:
      enabled: true