server:
  port: 9003

spring:
  profiles:
    active: mongodb,bannerNginx
  application:
    name: zillow-search
  elasticsearch:
    uris: http://111.231.19.137:9200
#eureka:
#  client:
#    service-url:
#      defaultZone: http://111.231.19.137:8761/eureka/
  instance:
    prefer-ip-address: true

zillow:
  banner:
    nginx:
      prefix: http://111.231.19.137:8888/

  search:
    init:
      enabled: true

logging:
  pattern:
    console: '%d{MM/dd HH:mm:ss.SSS} %clr(%-5level) ---  [%-15thread] %cyan(%-50logger{50}):%msg%n'