server:
  port: 8761

spring:
  application:
    name: zillow-eureka-server
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  security:
    basic:
      enabled: true
    user:
      name: admin
      password: admin

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/