server:
  port: 8761

spring:
  application:
    name: zillow-eureka-server
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false